// Bulgarian country names for the UI. English names come from the dataset
// (COUNTRY_META in build-data.mjs); we localize them for display only.
export const COUNTRY_BG = {
  USA: 'САЩ',
  UK: 'Обединено кралство',
  Germany: 'Германия',
  France: 'Франция',
  Canada: 'Канада',
  Australia: 'Австралия',
  Italy: 'Италия',
  Spain: 'Испания',
  Netherlands: 'Нидерландия',
  Belgium: 'Белгия',
  Sweden: 'Швеция',
  Switzerland: 'Швейцария',
  Greece: 'Гърция',
  Portugal: 'Португалия',
  Romania: 'Румъния',
  Poland: 'Полша',
  'Czech Republic': 'Чехия',
  Hungary: 'Унгария',
  Norway: 'Норвегия',
  Denmark: 'Дания',
  Finland: 'Финландия',
  Ireland: 'Ирландия',
  Ukraine: 'Украйна',
  Russia: 'Русия',
  Turkey: 'Турция',
  China: 'Китай',
  India: 'Индия',
  Japan: 'Япония',
  'South Korea': 'Южна Корея',
  Singapore: 'Сингапур',
  'Hong Kong': 'Хонконг',
  Malaysia: 'Малайзия',
  Indonesia: 'Индонезия',
  Thailand: 'Тайланд',
  Vietnam: 'Виетнам',
  Philippines: 'Филипини',
  Pakistan: 'Пакистан',
  Bangladesh: 'Бангладеш',
  Iran: 'Иран',
  Israel: 'Израел',
  'Saudi Arabia': 'Саудитска Арабия',
  Egypt: 'Египет',
  Nigeria: 'Нигерия',
  'South Africa': 'Южна Африка',
  Brazil: 'Бразилия',
  Mexico: 'Мексико',
  Argentina: 'Аржентина',
  Chile: 'Чили',
  Peru: 'Перу',
  Colombia: 'Колумбия',
  'New Zealand': 'Нова Зеландия',
  Bulgaria: 'България',
};

export const nameBg = (country) => COUNTRY_BG[country] || country;
